import type { Metadata } from "next";
import { Quicksand, Prosto_One } from "next/font/google";
import "./globals.css";

const prostoOne = Prosto_One({
  variable: "--font-prosto-one",
  subsets: ["latin"],
  weight: "400",
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: "500",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${quicksand.variable} ${prostoOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
